# Named vector with country/city mappings
entry_people_compund_name_map <- c(
  "LUDWIG SEDLACEK" = "Ludwig Sedlacek",
  "PACBIO" = "PacBio",
  "GERBION" = "Gerbion",
  "ISOLATE-SEQ" = "Isolate-seq", 
  "POP-SEQ" = "Pop-seq",
  "VLAD" = "Vlad", 
  "HAEMOPHILUS" = "Haemophilus", 
  "MICHAEL RASMUSSEN" = "Michael Rasmussen", 
  "JÖRG STEINMANN" = "Jörg Steinmann", 
  "GLENNAH" = "Glennah", 
  "BARBARA HAMMER" = "Barbara Hammer", 
  "KATHARINA KRANZER" = "Katharina Kranzer", 
  "CHLAMYDIA" = "Chlamydia",
  "KENSUKE SHIMA" = "Kensuke Shima",
  "KENSUKE" = "Kensuke Shima",
  "DELAMANID" = "Delamanid",
  "BAYM TEST" = "Baym test",
  "HAIN-TEST" = "Hain-test",
  "CEALAND" = "Cealand", 
  "SERRATIA" = "Serratia", 
  "OLENA" = "Olena", 
  "HAMILTON" = "Hamilton", 
  "INFLUENZA" = "Influenza",
  "LEILA" = "Leila", 
  "LIMA" = "Lima"
)